diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
core.symlinks=false
core.autocrlf=true
core.fscache=true
core.editor=notepad
color.diff=auto
color.status=auto
color.branch=auto
color.interactive=true
help.format=html
rebase.autosquash=true
credential.helper=C:/Program\ Files/Git/mingw64/bin/git-credential-manager.exe
http.proxy=http://:@rb-proxy-de.bosch.com:8080
http.sslverify=true
http.sslbackend=schannel
http.http://*.bosch.com/.proxy=
http.https://*.bosch.com/.proxy=
http.http://*.*.bosch.com/.proxy=
http.https://*.*.bosch.com/.proxy=
http.http://*.*.*.bosch.com/.proxy=
http.https://*.*.*.bosch.com/.proxy=
credential.https://sourcecode.socialcoding.bosch.com.provider=bitbucket
user.name=SAE7BP
user.email=bence.sandor2@hu.bosch.com
credential.http://rb-proxy-de.bosch.com:8080.provider=generic
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
remote.origin.url=https://github.com/sandorbence/BackendPractice.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.main.remote=origin
branch.main.merge=refs/heads/main
user.name=sandorbence
user.email=szaniszlo47@gmail.com
